stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script:
    - cpplint --verbose=0 include/control/control.h
    - cpplint --verbose=0 include/control/gain.h
    - cpplint --verbose=0 include/control/pid.h
  