stages:
  - lint

Lint:
  stage: lint
  tags:
    - bfs
  script: 
    - cpplint.py --verbose=0 --filter=-whitespace,-line_length,-readability,-braces, include/control/gain.h
    - cpplint.py --verbose=0 --filter=-whitespace,-line_length,-readability,-braces, include/control/pid.h
  